[project]
name = "extruct-web"
version = "0.1.0"
description = "my extruct web service"
requires-python = ">=3.11"

dependencies = [
    "fastapi==0.115.2",
    "uvicorn==0.32.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"