[project]
name = "extruct-web"
version = "0.1.0"
description = "my extruct web service"
requires-python = ">=3.11"

dependencies = [
    "fastapi==0.100.0",
    "uvicorn==0.30.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"